dependencies:
- id: node
  key: '{{ id }}-{{ agent.os }}-{{ agent.arch }}-{{ checksum "package-lock.json" }}'
  fallback_keys:
    - '{{ id }}-{{ agent.os }}-{{ agent.arch }}-'
  paths:
    - node_modules
- id: golang
  key: '{{ id }}-{{ agent.os }}-{{ agent.arch }}-{{ checksum "go.mod" }}'
  fallback_keys:
    - '{{ id }}-{{ agent.os }}-{{ agent.arch }}-'
  paths:
    - .gocache
    - .gomodcache
